apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.basename" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "gateway.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  # clusterIP: None
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector: {{- include "gateway.matchLabels" . | nindent 4 }}