apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.basename" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "backend.labels" . | nindent 4 }}
data:
  # modified config.py:
  # * support additional database
  config.py: |
    {{- .Files.Get "files/config.py" | nindent 4 }}