{{/*
Pod SecurityContext
*/}}
{{- define "podSecurityContext" -}}
securityContext: {}
{{- end -}}

{{/*
Container SecurityContext
*/}}
{{- define "containerSecurityContext" -}}
securityContext: {}
{{- end -}}