{{- if not .Values.persistence.existingPvc -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "basename" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- with .Values.persistence.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end}}
{{- end }}