{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "basename" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "labels" . | nindent 4 }}
stringData:
  TAIGA_SECRET_KEY: {{ .Values.secrets.TAIGA_SECRET_KEY | quote  }}
  TAIGA_SITES_DOMAIN: {{ .Values.ingress.hostname | quote }}
  TAIGA_SITES_SCHEME: {{ .Values.secrets.TAIGA_SITES_SCHEME | quote }}
  WEBSOCKETS_SCHEME:  {{ .Values.secrets.WEBSOCKETS_SCHEME | quote }}
  EMAIL_BACKEND: {{ .Values.secrets.EMAIL_BACKEND | quote }}
  DEFAULT_FROM_EMAIL: {{ .Values.secrets.DEFAULT_FROM_EMAIL | quote }}
  EMAIL_USE_TLS: {{ .Values.secrets.EMAIL_USE_TLS | quote }}
  EMAIL_USE_SSL: {{ .Values.secrets.EMAIL_USE_SSL | quote }}
  EMAIL_HOST: {{ .Values.secrets.EMAIL_HOST | quote }}
  EMAIL_PORT: {{ .Values.secrets.EMAIL_PORT | quote }}
  EMAIL_HOST_USER: {{ .Values.secrets.EMAIL_HOST_USER | quote }}
  EMAIL_HOST_PASSWORD: {{ .Values.secrets.EMAIL_HOST_PASSWORD | quote }}
  ENABLE_TELEMETRY: {{ .Values.secrets.ENABLE_TELEMETRY | quote }}
  ATTACHMENTS_MAX_AGE: {{ .Values.secrets.ATTACHMENTS_MAX_AGE | quote  }}
  CELERY_BROKER_URL: amqp://{{ .Values.rabbitmq.async.username }}:{{ .Values.rabbitmq.async.password }}@{{ .Values.rabbitmq.async.hostname }}:{{ .Values.rabbitmq.async.port }}/{{ .Values.rabbitmq.async.vhost }}
  EVENTS_PUSH_BACKEND_URL: amqp://{{ .Values.rabbitmq.events.username }}:{{ .Values.rabbitmq.events.password }}@{{ .Values.rabbitmq.events.hostname }}:{{ .Values.rabbitmq.events.port }}/{{ .Values.rabbitmq.events.vhost }}
  POSTGRES_OPTIONS: '-c search_path=public'
{{- end }}