{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "basename" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "labels" . | nindent 4 }}
stringData:
  {{- range $key, $value := .Values.config.secrets }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  CELERY_BROKER_URL: amqp://{{ .Values.rabbitmq.async.username }}:{{ .Values.rabbitmq.async.password }}@{{ .Values.rabbitmq.async.hostname }}:{{ .Values.rabbitmq.async.port }}/{{ .Values.rabbitmq.async.vhost }}
  EVENTS_PUSH_BACKEND_URL: amqp://{{ .Values.rabbitmq.events.username }}:{{ .Values.rabbitmq.events.password }}@{{ .Values.rabbitmq.events.hostname }}:{{ .Values.rabbitmq.events.port }}/{{ .Values.rabbitmq.events.vhost }}
  POSTGRES_OPTIONS: '-c search_path=public'
{{- end }}