apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "async.basename" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "async.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.async.deployment.replicas }}
  selector:
    matchLabels: {{- include "async.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "async.labels" . | nindent 8 }}
    spec:
      serviceAccount: {{ .Values.serviceAccount }}

      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 2000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      containers:
      - name: async

        image: {{ .Values.backend.deployment.image.repository }}:{{ .Values.backend.deployment.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.backend.deployment.image.imagePullPolicy }}

        {{- if .Values.debug.diagnoseMode.async.enabled }}
        command: {{- toYaml .Values.debug.diagnoseMode.async.command  | nindent 12 }}
        {{- else }}
        # modified entry point, as the original tries to change file permissions
        command:
          - bash
          - -c
          - |
            set -euo pipefail

            echo Starting Celery...
            celery -A taiga.celery worker -B \
              --concurrency 4 \
              -l INFO \
              "$@"
        {{- end}}

        {{- if .Values.async.deployment.resources }}
        resources: {{- toYaml .Values.async.deployment.resources | nindent 12 }}
        {{- end }}

        envFrom:
          - secretRef:
              name: {{ template "secret" . }}

        env:
          {{ include "postgresql.env" . | nindent 10 }}

        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]

        volumeMounts:
        - name: data
          subPath: static
          mountPath: /taiga-back/static
        - name: data
          subPath: media
          mountPath: /taiga-back/media
        - name: config
          subPath: config.py
          mountPath: /taiga-back/settings/config.py

      volumes:
      - name: data
        persistentVolumeClaim:
            claimName: {{ template "pvc" . }}
      - name: config
        configMap:
          name: {{ template "backend.basename" . }}
